package model

const templateMain = `// Code generated by {{.Generator}} {{.Version}}; DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"fmt"
	"strings"
	"xorkevin.dev/governor/service/db"
)
`
