package model

const templateModel = `// Code generated by {{.Generator}} {{.Version}}; DO NOT EDIT.

package {{.Package}}

import (
	"database/sql"
	"fmt"
	"strings"{{.Imports}}
)

const (
	{{.Prefix}}ModelTableName = "{{.TableName}}"
)

func {{.Prefix}}ModelSetup(db *sql.DB) error {
	_, err := db.Exec("CREATE TABLE IF NOT EXISTS {{.TableName}} ({{.SQL.Setup}});")
	if err != nil {
		return err
	}
	{{- range .SQL.Indicies }}
	_, err = db.Exec("CREATE INDEX IF NOT EXISTS {{$.TableName}}_{{.Name}}_index ON {{$.TableName}} ({{.Columns}});")
	if err != nil {
		return err
	}
	{{- end }}
	return nil
}

func {{.Prefix}}ModelInsert(db *sql.DB, m *{{.ModelIdent}}) error {
	_, err := db.Exec("INSERT INTO {{.TableName}} ({{.SQL.DBNames}}) VALUES ({{.SQL.Placeholders}});", {{.SQL.Idents}})
	if err != nil {
		return err
	}
	return nil
}

func {{.Prefix}}ModelInsertBulk(db *sql.DB, models []*{{.ModelIdent}}, allowConflict bool) error {
	conflictSQL := ""
	if allowConflict {
		conflictSQL = " ON CONFLICT DO NOTHING"
	}
	placeholders := make([]string, 0, len(models))
	args := make([]interface{}, 0, len(models)*{{.SQL.ColNum}})
	for c, m := range models {
		n := c * {{.SQL.ColNum}}
		placeholders = append(placeholders, fmt.Sprintf("({{.SQL.PlaceholderTpl}})", {{.SQL.PlaceholderCount}}))
		args = append(args, {{.SQL.Idents}})
	}
	_, err := db.Exec("INSERT INTO {{.TableName}} ({{.SQL.DBNames}}) VALUES "+strings.Join(placeholders, ", ")+conflictSQL+";", args...)
	if err != nil {
		return err
	}
	return nil
}
`
