.nh
.TH "forge" "1" "Apr 2023" "" ""

.SH NAME
.PP
forge-doc-md - generate markdown documentation for forge


.SH SYNOPSIS
.PP
\fBforge doc md [flags]\fP


.SH DESCRIPTION
.PP
generate markdown documentation for forge


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for md


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--log-json\fP[=false]
	output json logs

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH SEE ALSO
.PP
\fBforge-doc(1)\fP
