.nh
.TH "forge" "1" "Oct 2021" "" ""

.SH NAME
.PP
forge \- A code generation utility


.SH SYNOPSIS
.PP
\fBforge [flags]\fP


.SH DESCRIPTION
.PP
A code generation utility for governor to generate common files instead
of writing them by hand.


.SH OPTIONS
.PP
\fB\-\-config\fP=""
	config file (default is $XDG\_CONFIG\_HOME/.forge.yaml)

.PP
\fB\-\-debug\fP[=false]
	turn on debug output

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for forge


.SH SEE ALSO
.PP
\fBforge\-completion(1)\fP, \fBforge\-doc(1)\fP, \fBforge\-model(1)\fP, \fBforge\-validation(1)\fP
