.nh
.TH "forge" "1" "Aug 2023" "" ""

.SH NAME
.PP
forge - A code generation utility


.SH SYNOPSIS
.PP
\fBforge [flags]\fP


.SH DESCRIPTION
.PP
A code generation utility for governor to generate common files instead
of writing them by hand.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for forge

.PP
\fB--log-json\fP[=false]
	output json logs

.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBforge-completion(1)\fP, \fBforge-doc(1)\fP, \fBforge-model(1)\fP, \fBforge-validation(1)\fP
