.nh
.TH "forge" "1" "Jan 2024" "" ""

.SH NAME
.PP
forge-doc-man - generate man page documentation for forge


.SH SYNOPSIS
.PP
\fBforge doc man [flags]\fP


.SH DESCRIPTION
.PP
generate man page documentation for forge


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for man


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--log-json\fP[=false]
	output json logs

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH SEE ALSO
.PP
\fBforge-doc(1)\fP
